import Head from 'next/head'

import React, { Suspense } from 'react';

const Spline = React.lazy(() => import('@splinetool/react-spline'));


export default function Home() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='h-full'>
        <Suspense fallback={<div>Loading...</div>}>
          <Spline scene="https://prod.spline.design/0IMRhFLFvck929HZ/scene.splinecode" />
        </Suspense>
      </main>

    </div>
  )
}
